-- Seed crm_fields table with all 71 fields from Excel
INSERT INTO crm_fields (field_name, display_name, section, field_type, is_system_field, sort_order, dropdown_options, file_config) VALUES
  -- LEAD fields (1-10)
  ('first_name', 'First Name', 'LEAD', 'text', true, 1, null, null),
  ('middle_name', 'Middle Name', 'LEAD', 'text', false, 2, null, null),
  ('last_name', 'Last Name', 'LEAD', 'text', true, 3, null, null),
  ('phone', 'Phone', 'LEAD', 'phone', true, 4, null, null),
  ('email', 'Email', 'LEAD', 'email', true, 5, null, null),
  ('referred_via', 'Referral Method', 'LEAD', 'select', false, 6, '["EMAIL", "TEXT", "CALL", "WEB", "IN-PERSON"]'::jsonb, null),
  ('referral_source', 'Referral Source', 'LEAD', 'select', false, 7, '["AGENT", "PAST CLIENT", "PERSONAL", "SOCIAL", "MISC"]'::jsonb, null),
  ('converted', 'Lead Status', 'LEAD', 'select', true, 8, '["Working on it", "Converted", "Nurture", "Dead"]'::jsonb, null),
  ('monthly_pmt_goal', 'Monthly Pmt Goal', 'LEAD', 'currency', false, 9, null, null),
  ('cash_to_close_goal', 'Cash to Close Goal', 'LEAD', 'currency', false, 10, null, null),
  
  -- APP COMPLETE fields (11-34)
  ('loan_type', 'Transaction Type', 'APP COMPLETE', 'select', false, 11, '["PURCHASE", "REFINANCE", "HELOC"]'::jsonb, null),
  ('income_type', 'Income Type', 'APP COMPLETE', 'select', false, 12, '["FULL DOC - SALARY", "FULL DOC - S/E", "ALT DOC - DSCR", "ALT DOC - BANK STATEMENT"]'::jsonb, null),
  ('reo', 'REO?', 'APP COMPLETE', 'boolean', false, 13, null, null),
  ('property_type', 'Property Type', 'APP COMPLETE', 'select', false, 14, '["SINGLE FAMILY HOME", "CONDO", "MULTI-FAMILY", "TOWNHOUSE", "COMMERCIAL"]'::jsonb, null),
  ('occupancy', 'Occupancy', 'APP COMPLETE', 'select', false, 15, '["PRIMARY HOME", "SECOND HOME", "INVESTMENT PROPERTY"]'::jsonb, null),
  ('borrower_current_address', 'Borrower Current Address', 'APP COMPLETE', 'text', false, 16, null, null),
  ('own_rent_current_address', 'Own/Rent Current Address?', 'APP COMPLETE', 'select', false, 17, '["RENT", "OWN"]'::jsonb, null),
  ('time_at_current_address_years', 'Time at Address (Years)', 'APP COMPLETE', 'number', false, 18, null, null),
  ('time_at_current_address_months', 'Time at Address (Months)', 'APP COMPLETE', 'number', false, 19, null, null),
  ('military_veteran', 'Military/Veteran?', 'APP COMPLETE', 'boolean', false, 20, null, null),
  ('dob', 'Date of Birth', 'APP COMPLETE', 'date', false, 21, null, null),
  ('estimated_fico', 'Estimated FICO', 'APP COMPLETE', 'number', false, 22, null, null),
  ('loan_amount', 'Loan Amount', 'APP COMPLETE', 'currency', false, 23, null, null),
  ('sales_price', 'Sales Price', 'APP COMPLETE', 'currency', false, 24, null, null),
  ('down_pmt', 'Down Pmt', 'APP COMPLETE', 'text', false, 25, null, null),
  ('term', 'Term (Amortization)', 'APP COMPLETE', 'select', false, 26, '["480", "360", "300", "240", "180", "120"]'::jsonb, null),
  ('monthly_liabilities', 'Monthly Liabilities', 'APP COMPLETE', 'currency', false, 27, null, null),
  ('assets', 'Assets', 'APP COMPLETE', 'currency', false, 28, null, null),
  ('subject_address_1', 'Subject Address 1', 'APP COMPLETE', 'text', false, 29, null, null),
  ('subject_address_2', 'Subject Address 2', 'APP COMPLETE', 'text', false, 30, null, null),
  ('subject_city', 'Subject City', 'APP COMPLETE', 'text', false, 31, null, null),
  ('subject_state', 'Subject State', 'APP COMPLETE', 'text', false, 32, null, null),
  ('subject_zip', 'Subject Zip', 'APP COMPLETE', 'text', false, 33, null, null),
  ('arrive_loan_number', 'Arrive Loan #', 'APP COMPLETE', 'number', false, 34, null, null),
  
  -- APP REVIEW fields (35-41, 68-72)
  ('interest_rate', 'Interest Rate', 'APP REVIEW', 'percentage', false, 35, null, null),
  ('piti', 'PITI', 'APP REVIEW', 'currency', false, 36, null, null),
  ('program', 'Program', 'APP REVIEW', 'select', false, 37, '["CONVENTIONAL", "JUMBO", "NON-QM", "FHA", "VA", "PRIVATE"]'::jsonb, null),
  ('total_monthly_income', 'Total Monthly Income', 'APP REVIEW', 'currency', false, 38, null, null),
  ('escrows', 'Escrows', 'APP REVIEW', 'select', false, 39, '["WAIVED", "NOT WAIVED"]'::jsonb, null),
  ('dti', 'DTI', 'APP REVIEW', 'percentage', false, 40, null, null),
  ('close_date', 'Close Date', 'APP REVIEW', 'date', false, 41, null, null),
  ('principal_interest', 'Principal & Interest', 'APP REVIEW', 'currency', false, 68, null, null),
  ('property_taxes', 'Property Taxes', 'APP REVIEW', 'currency', false, 69, null, null),
  ('homeowners_insurance', 'Homeowners Insurance', 'APP REVIEW', 'currency', false, 70, null, null),
  ('mortgage_insurance', 'Mortgage Insurance', 'APP REVIEW', 'currency', false, 71, null, null),
  ('hoa_dues', 'HOA Dues', 'APP REVIEW', 'currency', false, 72, null, null),
  
  -- ACTIVE fields (42-67)
  ('disclosure_status', 'Disclosures', 'ACTIVE', 'select', false, 42, '["ORDERED", "SENT", "SIGNED"]'::jsonb, null),
  ('loan_status', 'Loan Status', 'ACTIVE', 'select', true, 43, '["New", "RFP", "SUB", "AWC", "CTC", "CLOSED"]'::jsonb, null),
  ('appraisal_status', 'Appraisal Status', 'ACTIVE', 'select', false, 44, '["ORDERED", "SCHEDULED", "INSPECTED", "RECEIVED", "WAIVER", "TRANSFER"]'::jsonb, null),
  ('title_status', 'Title Status', 'ACTIVE', 'select', false, 45, '["ORDERED", "RECEIVED"]'::jsonb, null),
  ('hoi_status', 'HOI Status', 'ACTIVE', 'select', false, 46, '["QUOTED", "ORDERED", "BOUND"]'::jsonb, null),
  ('mi_status', 'MI Status', 'ACTIVE', 'select', false, 47, '["REQUESTED", "RECEIVED", "N/A"]'::jsonb, null),
  ('condo_status', 'Condo Status', 'ACTIVE', 'select', false, 48, '["ORDERED", "RECEIVED", "RECEIVED - NEED CORRECTIONS", "APPROVED", "N/A"]'::jsonb, null),
  ('cd_status', 'CD Status', 'ACTIVE', 'select', false, 49, '["SENT", "SIGNED"]'::jsonb, null),
  ('package_status', 'Package Status', 'ACTIVE', 'select', false, 50, '["IN PROGRESS", "FINALIZED"]'::jsonb, null),
  ('ba_status', 'BA Status', 'ACTIVE', 'select', false, 51, '["SEND", "SENT", "SIGNED", "N/A"]'::jsonb, null),
  ('epo_status', 'EPO Status', 'ACTIVE', 'select', false, 52, '["SEND", "SENT", "SIGNED", "N/A"]'::jsonb, null),
  ('lock_expiration_date', 'Lock Expiration Date', 'ACTIVE', 'date', false, 53, null, null),
  ('title_eta', 'Title ETA', 'ACTIVE', 'date', false, 54, null, null),
  ('appr_date_time', 'Appraisal Date/Time', 'ACTIVE', 'datetime', false, 55, null, null),
  ('appr_eta', 'Appraisal ETA', 'ACTIVE', 'date', false, 56, null, null),
  ('appraisal_value', 'Appraisal Value', 'ACTIVE', 'text', false, 57, null, null),
  ('fin_cont', 'Financing Contingency', 'ACTIVE', 'date', false, 58, null, null),
  ('les_file', 'LES File', 'ACTIVE', 'file', false, 59, null, '{"storage_path": "files/{lead_id}/les/", "allowed_types": [".pdf"]}'::jsonb),
  ('contract_file', 'Contract File', 'ACTIVE', 'file', false, 60, null, '{"storage_path": "files/{lead_id}/contract/", "allowed_types": [".pdf"]}'::jsonb),
  ('initial_approval_file', 'Initial Approval File', 'ACTIVE', 'file', false, 61, null, '{"storage_path": "files/{lead_id}/initial_approval/", "allowed_types": [".pdf"]}'::jsonb),
  ('disc_file', 'Disclosures File', 'ACTIVE', 'file', false, 62, null, '{"storage_path": "files/{lead_id}/disclosures/", "allowed_types": [".pdf"]}'::jsonb),
  ('appraisal_file', 'Appraisal File', 'ACTIVE', 'file', false, 63, null, '{"storage_path": "files/{lead_id}/appraisal/", "allowed_types": [".pdf"]}'::jsonb),
  ('insurance_file', 'Insurance File', 'ACTIVE', 'file', false, 64, null, '{"storage_path": "files/{lead_id}/insurance/", "allowed_types": [".pdf"]}'::jsonb),
  ('icd_file', 'ICD File', 'ACTIVE', 'file', false, 65, null, '{"storage_path": "files/{lead_id}/icd/", "allowed_types": [".pdf"]}'::jsonb),
  ('fcp_file', 'FCP File', 'ACTIVE', 'file', false, 66, null, '{"storage_path": "files/{lead_id}/fcp/", "allowed_types": [".pdf"]}'::jsonb),
  
  -- Additional fields
  ('search_stage', 'Search Stage', 'PRE_APPROVED', 'select', false, 73, '["JUST LOOKING", "SHOPPING", "OFFERS OUT", "UNDER CONTRACT", "LONG TERM"]'::jsonb, null)
ON CONFLICT (field_name) DO NOTHING;