// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpsvatonxakysnbqnfcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpwc3ZhdG9ueGFreXNuYnFuZmNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMTg2NTAsImV4cCI6MjA3MDY5NDY1MH0.CcjsfGGYq43oN13uK8a9LAfAaytnHm4FNqJWe3n_ZoQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: window.sessionStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});